## Column wise average for 2D array

If you have a 2D array, you have to take the average column wise and save it in a 1D array.

#### Method 1 : traditional python

In [ ]:
l1  = [[1,99,3,4], [2,23, 4,5], [3,34,5,6], [4,67,6,7]]
m1 = [0 for i in range(len(l1[0]))]
row_cnt = 0
for i in l1:
  colum_cnt = 0
  for j in i :
      m1[colum_cnt] = m1[colum_cnt] + j
      if colum_cnt >= len(m1) :
        colum_cnt = 0
      if row_cnt == (len(l1) - 1) :
        #print(row_cnt, colum_cnt)
        m1[colum_cnt] = m1[colum_cnt] / len(l1)
      colum_cnt += 1
  row_cnt += 1
 

In [ ]:
m1

[2.5, 55.75, 4.5, 5.5]

#### Method 2 : DS Python

In [ ]:
import numpy as np

arr = np.array(l1)
arr

array([[ 1, 99,  3,  4],
       [ 2, 23,  4,  5],
       [ 3, 34,  5,  6],
       [ 4, 67,  6,  7]])

In [ ]:
np.mean(arr, axis = 0)

array([ 2.5 , 55.75,  4.5 ,  5.5 ])

## Average index Array

#### Create a 2D array in which values are in each index is the average of that particular row index & column index in that location.

In [ ]:
x=3
y=4
#write your code here
import numpy as np
arr = np.zeros((x,y))

for i in range(0, x) :
    for j in range(0, y) :
        arr[i][j] = (i + j) / 2
        
print(arr)

[[0.  0.5 1.  1.5]
 [0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5]]
